### ISSUE TITLE
Negative infinity

### ISSUE THREAD

**Issue by peterdfields** [gbradburd/SpaceMix#7]
I get the following error when running spacemix:

fast run 1 failed 
Error in MCMC(model.option = fast.model.option, data.type = data.type, : Initial probability of model is NEGATIVE INFINITY! Please attempt to initiate chain again.

skipping fast_run_1 because it failed 
Error in setwd(list.files()[grep("BestRun", list.files())]) : 
  character argument expected
In addition: Warning messages:
1: In sqrt(mean.freq.mat \* (1 - mean.freq.mat)) : NaNs produced
2: In sqrt(mean.freq.mat \* (1 - mean.freq.mat)) : NaNs produced
3: In file.rename(paste("../", fast.run.dirs[i], sep = ""), paste("../",  :
  cannot rename file '../fast_run_1' to '../failed_fast_run_1', reason 'Directory not empty'
4: In file.rename(fast.run.dirs[which.max(last.probs)], paste(fast.run.dirs[which.max(last.probs)],  :
  cannot rename file 'fast_run_1' to 'fast_run_1_BestRun', reason 'No such file or directory'

I tried initiating the MCMC a number of times but always get this error. The present dataset is using only a single individual per population, about 50k SNPs. Let me know if any additional info that might be useful troubleshooting here.

**Comment by gbradburd** [comment]
Looks like you're generating NaNs when you're estimating the sample-size-weighted mean allele frequencies at each locus with the function "get.weighted.mean.frequency."  My guess would be that you have some missing data, and that the missing data are characterized as 0 in your "sample.sizes" matrix but not 0 in your "counts" data matrix.  In R, 0/0 evaluates to NaN, and integer/0 evaluates to Inf.  NaN values are ignored by the "get.weighted.mean.frequency" function, but Inf values are not, so you get mean allele frequencies that are Inf, and sqrt(Inf*(1-Inf)) evaluates to NaNs (and throws the warning that you saw).

So, I'd check that first, and if you can't find the problem, email me your data files as a .Robj along with the script you're using to run your analysis and I'll take a look.
