### ISSUE TITLE
Plotting admixture when there is no admixture

### ISSUE THREAD

**Issue by andersgs** [gbradburd/SpaceMix#9]
Hi Gideon.

Thank you for the great package, and method!

I am running the 'source_and_target' mode, and there seems to be little evidence for admixture. Yet, when I make the geogenetic plot, I get large dotted circles that encompass all populations. Is this by design?

Also, as a minor suggestion, you should add a citation and link to the paper to the repo's README.

Thanks again.

Best.

Anders.

**Comment by gbradburd** [comment]
Thanks Anders!  If you set "source.option" to "FALSE" in the function make.spacemix.map(), those dotted circles will not be plotted.  If you then want to plot the admixture arrows for specific samples, you can do so using query.spacemix.map().

Thanks for the suggestion about the citation & link in the README!

**Comment by gbradburd** [comment]
Also note that when admixture proportions are very small, the credible interval on admixture source location parameters becomes very large, and you're essentially just recovering the prior.  The default values of the prior on the admixture source locations make a bivariate normal with a large variance and a mean at the centroid of all sample locations, so when you see those large dotted circles encompassing all the observed sample locations and very low admixture proportions, you're probably just seeing that prior.

**Comment by andersgs** [comment]
Hi Gideon.

Thank you very much. Yes, your comment about the prior makes sense with my data.

Thanks again.

Anders.
